<?php
use Migrations\AbstractSeed;

/**
 * Projects seed.
 */
class ProjectsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
          [
            "id" => 1,
        		"name" => "Seg-Social Seg. Social M\u00f3vil",
        		"slug" => preg_replace('/[[:space:]]+/', '-', strtolower("Seg-Social Seg. Social Movil")) . '-' . uniqid(),
        		"description" => "This application provides access to all information that the Secretary of State of the Spanish Social Security makes available to the citizens. The application allows users to:\n- Obtain certificates, consultations and personal accounts for Social Security.\n- Get prior appointment for procedures in Social Security offices.\n- Get contact information for the different entities managing Social Security.\n- Consult the nearest office to its present location.\n- Check the location of hospitas.\n- Access via link to the main information websites of Social Security.\n- Be informed of the latest developments in Social Security.",
        		"image" => "https://clarity-csa.eu/sites/default/files/styles/large/public/portfolio/movil%20kopya.jpg?itok=mC2AWVF6",
        		"type" => "Tools",
        		"country" => "Spain",
        		"category" => "General practice health",
        		"organisation" => "Ministry of Health, Social Services and Equality, Regional Government",
        		"website" => "https://play.google.com/store/apps/details?id=gov.es.segsocial.lanzadera",
            'published' => true,
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s'),
            'group_id' => 4
          ],
          [
            "id" => 2,
        		"group_id" => 4,
        		"name" => "Opinion Service",
        		"slug" => preg_replace('/[[:space:]]+/', '-', strtolower("Opinion Service")) . '-' . uniqid(),
        		"description" => "Lausuntopalvelu.fi is a web service that implements public opinion dissemination as an electronic service.\r\nThe purpose of the service is to intensify the consultation process by providing citizens, organizations and authorities with a consistent online service where the requests for referrals can be published, issued statements and processed opinions.",
        		"image" => "https://clarity-csa.eu/sites/default/files/styles/large/public/portfolio/opinion%20service.jpg?itok=0lYJnLe5",
        		"type" => "Use Case",
        		"country" => "Finland",
        		"category" => "Local government services",
        		"organisation" => "The Ministry of Justice",
        		"website" => "https://www.lausuntopalvelu.fi",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s'),
          ],
          [
            "id" => 3,
        		"group_id" => 4,
        		"name" =>"Digital Austria",
        		"slug" => preg_replace('/[[:space:]]+/', '-', strtolower("Digital Austria")) . '-' . uniqid(),
        		"description" => "Government portals team up with each other to form a portal group and share the existing infrastructure.",
        		"image" => "https://clarity-csa.eu/sites/default/files/styles/large/public/portfolio/Digital_Austria-logo-24F7FA8340-seeklogo.com_.gif?itok=IJ6rIkBP",
        		"type" => "Use Case",
        		"country" => "Austria",
        		"category" => "National Government Services",
        		"organisation" => "Federal Government",
        		"website" => "https://www.digital.austria.gv.at",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s'),
          ],
          [
            "id" => 4,
        		"group_id" => 4,
        		"name" => "Mocca",
        		"slug" => preg_replace('/[[:space:]]+/', '-', strtolower("Mocca")) . '-' . uniqid(),
        		"description" => "The Citizen Card provided by Austrian government requires a separate Citizen Card Environment for local use. Mocca (Modular Open Citizen Card Architecture) is recommended by the Federal Chancellery. The software is free and open source. ",
        		"image" => "https://clarity-csa.eu/sites/default/files/styles/large/public/portfolio/mocca-logo%20kopya.jpg?itok=yfZgqsDl",
        		"type" => "Tools",
        		"country" => "Austria",
        		"category" => "Local government services",
        		"organisation" => "Federal Government",
        		"website" => "https://www.buergerkarte.at",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s'),
          ],
          [
            "id" => 5,
        		"group_id" => 4,
        		"name" => "Amtsfinder",
        		"slug" => preg_replace('/[[:space:]]+/', '-', strtolower("Amtsfinder")) . '-' . uniqid(),
        		"description" => "The Federal Chancellery of Austria will lead you reliably to your nearest competent authority with the \"Amtsfinder\" -App from HELP.gv.at. It provides information on all interactions with Austrian authorities required in the most frequent life situations such as pregnancy, childbirth, marriage or housing, and permits the electronic processing of some of these procedures. Furthermore, the fastest route from your location to the nearest office is displayed at the push of a button. The app is supplemented by the official emergency numbers and service hotlines of the Federal Ministries, which can be selected directly by means of a button. ",
        		"image" => "https://clarity-csa.eu/sites/default/files/styles/large/public/portfolio/amtsfinder.png?itok=S78qRy84",
        		"type" => "Tools",
        		"country" => "Austria",
        		"category" => "Local government services",
        		"organisation" => "Central Government (Federation) / Local Government (Municipalities)",
        		"website" => "https://play.google.com/store/apps/details?id=at.gv.help.amtsfinder",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],
          [
            "id" => 6,
        		"group_id" => 4,
        		"name" => "MyMaidstone",
        		"slug" => preg_replace('/[[:space:]]+/', '-', strtolower("MyMaidStone")) . '-' . uniqid(),
        		"description" => "My Maidstone is the official app of Maidstone Borough Council. Citizens can contact with the council, pay for services, and get local information.",
        		"image" => "https://clarity-csa.eu/sites/default/files/styles/large/public/portfolio/maidstone.jpg?itok=_LgVsIkX",
        		"type" => "Tools",
        		"country" => "United Kingdom",
        		"category" => "Local government services",
        		"organisation" => "Maidstone Council",
        		"website" => "https://itunes.apple.com/gb/app/mymaidstone/id1172055993?mt=8",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],
          [
            "id" => 7,
        		"group_id" => 4,
        		"name" => "Our Haringey",
        		"slug" => preg_replace('/[[:space:]]+/', '-', strtolower("Our Haringey")) . '-' . uniqid(),
        		"description" => "The Our Haringey app makes it quick and easy to report problems when citizens are out and about in the borough. It is possible to report a range of problems, from dumped rubbish to graffiti, and users will be updated about the progress fixing them.",
        		"image" => "https://clarity-csa.eu/sites/default/files/styles/large/public/portfolio/our%20haringey.jpeg?itok=B-0pbTAx",
        		"type" => "Tools",
        		"country" => "United Kingdom",
        		"category" => "Civic Participation",
        		"organisation" => "Haringey Council",
        		"website" => "https://play.google.com/store/apps/details?id=uk.co.bbits.LoveHaringey",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],
          [
            'id' => 8,
            'name' => 'OGP Toolbox',
            "slug" => preg_replace('/[[:space:]]+/', '-', strtolower("OGP Toolbox")) . '-' . uniqid(),
            'description'   => 'The OGP Toolbox is a free software initially developed by Etalab, the Prime Minister taskforce in charge of open data and open government French policy, on behalf of the Open Government Partnership community. Co-created by the open government and the civic tech international community throughout 2016, the OGP Toolbox is one of the main deliverables of the OGP Global Summit hackathon (7, 8 and 9 December 2016). In order to guarantee sustainability, independence and the capacity to associate various actors at the international level in the long term, the governance of the project has, since, evolved. In February 2017, the OGPToolbox.org association was created to fulfill the mission associated to the platform. The object of the association is to empower public, private and civil society actors worldwide by sharing digital tools and resources, in order to promote democracy, transparency, participation and collaboration. The goals of the association, using the OGPToolbox.org platform and every means at its disposal, are to: allow actors to identify the digital tools better suited to their needs, by collecting and describing them in the most objective way possible; collaborate to make digital tools more accessible and easier to use; create favourable conditions to further the development of better digital tools; foster the sharing of experience between actors and giving feedback on existing tools. To participate to the activities of the OGPToolbox.org association, follow the latest news on the forum.',
            'image'   => 'https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAArrAAAAJDI3ZDk5NWNmLTk0OGUtNDQ2OS04YWU0LTVhYzRkNGMwYmJlYg.jpg',
            'type' => 'Catalog',
            'country' => 'France',
            'organisation' => 'OGPToolbox.org association',
            'website' => 'https://ogptoolbox.org',
            'published' => true,
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s'),
            'group_id' => 20
          ],[
            "id" => 9,
        		"group_id" => 20,
        		"name" => "Amsterdam Smart City",
        		"slug" => preg_replace('/[[:space:]]+/', '-', strtolower("Amsterdam Smart City")) . '-' . uniqid(),
        		"description" => "Amsterdam Smart City has the ambition to become the largest smart city innovation platform in Amsterdam. It is our goal to create an overview of what is happening in Amsterdam on these themes. This will help us to connect the right people to accelerate the start of projects and tackle the challenges our city is facing. \r\n\r\nAmsterdam Smart City creates the overview of the ecosystem, connects communities to share expertise and kickstarts, accelerates and strengthens new projects that make the city futureproof!\r\n\r\nBy challenging parties to submit and execute innovative solutions to urban issues, ASC connects the right stakeholders and accelerates this progress. This advances the development of new markets and profits for innovative solutions. Where possible, these solutions are replicated elsewhere in the city.\r\n\r\nAmsterdam Smart City works with everyone who has the energy and ambitions to improve the liveability in the city. These can be companies, governments, knowledge institutions and citizens.",
        		"image" => "https://smartcity.imgix.net/page_featured_image/c_2375118594_2101_2570057158.jpeg?auto=format&h=371&w=600",
        		"type" => "search platform",
        		"country" => "Netherlands",
        		"organisation" => "Amsterdam Smart City",
        		"website" => "https://amsterdamsmartcity.com/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 10,
        		"group_id" => 20,
        		"name" => "Code for America Github",
        		"slug" => preg_replace('/[[:space:]]+/', '-', strtolower("Code For America Github")) . '-' . uniqid(),
        		"description" => "Overview of github repositories for Code for America projects.",
        		"image" => "http://www.codeforamerica.org/assets/CfA_logo_metatag_square.png",
        		"type" => "Projects overview",
        		"country" => "United States of America",
        		"organisation" => "Code for America",
        		"website" => "https://codeforamerica.github.io/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 11,
        		"group_id" => 20,
        		"name" => "Civic Tech Project Search",
        		"slug" => "project-search-50219f7e",
        		"description" => "Code for America Brigades are volunteer groups that collaborate with local government and community partners to build new tools that help with local civic issues. Code for America supports Brigade chapters with resources, tools, and access to the wider civic technology movement.",
        		"image" => "http://www.codeforamerica.org/assets/CfA_logo_metatag_square.png",
        		"type" => "search platform",
        		"country" => "United States of America",
        		"organisation" => "Code for America",
        		"website" => "http://brigade.codeforamerica.org/brigade/projects",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 12,
        		"group_id" => 20,
        		"name" => "Koduj Dla Polski",
        		"slug" => "koduj-dla-polski-50219f7e",
        		"description" => "Overview of Code for Poland (Kuduj Dla Polski) projects.",
        		"image" => "https://pbs.twimg.com/profile_images/801085552468619264/jujUx_6H_400x400.jpg",
        		"type" => "search platform",
        		"country" => "Poland",
        		"organisation" => "Koduj Dla Polski",
        		"website" => "https://codeforpoland.org/projects/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 13,
        		"group_id" => 20,
        		"name" => "Code for Romania project overview",
        		"slug" => "code-for-romania-project-overview-50219f7e",
        		"description" => "We want all the projects developed by our community to be simple to use and meet the needs of as many people as possible. This can be a map of city first-aid points, a site that explains the law to everyone, or an application that measures queue time in public institutions.\r\n\r\nOr any other idea, as long as it is feasible, solves a community problem or gives citizens access to public interest data.",
        		"image" => "https://code4.ro/wp-content/themes/code4/dist/images/brand-logotype.png",
        		"type" => "project overview",
        		"country" => "Romania",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 15,
        		"group_id" => 20,
        		"name" => "Clarity Marketplace",
        		"slug" => "clarity-marketplace-50219f7e",
        		"description" => "The Clarity Marketplace shows tools and use cases from Europe. Many interesting applications are being created in the field of Open eGovernment. The Marketplace helps local governments search and find current and emerging platforms, tools and apps. Where available download links are provided in order to replicate the technology.",
        		"image" => "https://clarity-csa.eu/sites/default/files/clarity_logo.jpg",
        		"type" => "search platform",
        		"country" => "Greece",
        		"organisation" => "Clarity Project (no org)",
        		"website" => "https://clarity-csa.eu/portfolio-clean-2cols",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 16,
        		"group_id" => 21,
        		"name" => "data.overheid.nl",
        		"slug" => "data-overheid-nl-50219f7e",
        		"description" => "Dit dataportaal bestaat uit een register met informatie over- en verwijzingen naar datasets van Nederlandse overheden. Daarnaast bieden we ondersteuning bij het openbaar maken van data. Dat doen we door feedback te verwerken, te helpen bij het aanmelden en zoeken van datasets en door bij te dragen aan kennis over open data.",
        		"image" => "https://data.overheid.nl/sites/all/themes/koop2/images/logo.png",
        		"type" => "dataportaal",
        		"country" => "Nederland",
        		"organisation" => "Ministerie van Binnenlandse Zaken en Koninkrijksrelaties",
        		"website" => "https://data.overheid.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 17,
        		"group_id" => 21,
        		"name" => "Amsterdam City Data",
        		"slug" => "amsterdam-city-data-50219f7e",
        		"description" => "Amsterdam City Data is het dataportaal van de gemeente Amsterdam. Hiermee kun je gegevens van de stad raadplegen.",
        		"image" => "https://zoek.officielebekendmakingen.nl/stcrt-2014-37951-1.png",
        		"type" => "dataportaal",
        		"country" => "Nederland",
        		"organisation" => "Gemeente Amsterdam",
        		"website" => "https://data.amsterdam.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 18,
        		"group_id" => 21,
        		"name" => "Rotterdam Open Data Store",
        		"slug" => "rotterdam-open-data-store-50219f7e",
        		"description" => "Rotterdam Open Data Store",
        		"image" => "https://i.vimeocdn.com/portrait/4453491_300x300",
        		"type" => "dataportaal",
        		"country" => "Nederland",
        		"organisation" => "Gemeente Rotterdam",
        		"website" => "http://rotterdamopendata.nl/dataset",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 19,
        		"group_id" => 21,
        		"name" => "Utrecht Open Data",
        		"slug" => "utrecht-open-data-50219f7e",
        		"image" => "https://pbs.twimg.com/profile_images/481738303318679553/V7PdBlJ0_400x400.png",
        		"type" => "dataportaal",
        		"country" => "Nederland",
        		"organisation" => "Gemeente Utrecht",
        		"website" => "https://utrecht.dataplatform.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 20,
        		"group_id" => 21,
        		"name" => "Dataplatform.nl",
        		"slug" => "dataplatformnl-50219f7e",
        		"description" => "Dataplatform is een initiatief van Civity. De belangrijkste doelstelling is om samen met overheden, bedrijven en kennisinstellingen het potentieel van (open) data te benutten. Civity ondersteunt de deelnemers aan Dataplatform met (infrastructurele) diensten, kennis, bijeenkomsten en projecten. Civity is ook \u00e9\u00e9n van de initiatiefnemers van FIWARE Lab NL, een gratis ontwikkelomgeving voor data- en Internet of Thingstoepassingen.\r\n\r\nDataplatform is een dienst voor elke organisatie om data op een makkelijke en veilige manier te ontsluiten, op te slaan, te beheren en te presenteren. Dataplatform is volledig gebaseerd op open source software (waaronder CKAN en Drupal). Data kan beschikbaar gesteld worden aan alle ge\u00efnteresseerden, maar ook alleen gedeeld worden binnen uw eigen organisatie of met partners. Met Dataplatform bepaalt u hoe en met wie uw data wilt delen.",
        		"image" => "https://www.dataplatform.nl/sites/all/themes/custom/ckan_dataplatform/images/logo.svg",
        		"type" => "dataportaal",
        		"country" => "Nederland",
        		"organisation" => "Civity",
        		"website" => "https://www.dataplatform.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 21,
        		"group_id" => 21,
        		"name" => "Nationaal Georegister",
        		"slug" => "nationaal-georegister-50219f7e",
        		"description" => "Het Nationaal Georegister is d\u00e9 vindplaats van geo-informatie van Nederland. Met de eenvoudige zoekopties en presentatie van resultaten kunnen de datasets in de kaartviewer worden bekeken of worden gedownload.",
        		"image" => "http://www.nationaalgeoregister.nl/geonetwork/catalog/views/ngr/images/NGRlogo.png",
        		"type" => "dataportaal",
        		"country" => "Nederland",
        		"category" => "geo",
        		"organisation" => "PDOK",
        		"website" => "http://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/home",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 22,
        		"group_id" => 21,
        		"name" => "Open Data Nederland",
        		"slug" => "open-data-nederland-50219f7e",
        		"description" => "Wij vinden het geweldig dat er zoveel open data van Nederland beschikbaar is. Vaak staat deze open data op de website van de uitgevende instantie vermeld. Helaas zijn deze websites lang niet bij iedereen bekend. OpenDataNederland.org lost dit op door de beschrijvingen van alle Nederlandse open datasets in \u00e9\u00e9n catalogus te bundelen en doorzoekbaar te maken. Daarnaast hebben we een Checklist voor aanbieders gemaakt zodat deze nog beter hun data kunnen aanbieden.",
        		"image" => "https://opendatanederland.org/Content/img/logo-open-data-nederland.png",
        		"type" => "dataportaal",
        		"country" => "Nederland",
        		"organisation" => "Oxyva",
        		"website" => "https://opendatanederland.org/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 23,
        		"group_id" => 21,
        		"name" => "Open Spending",
        		"slug" => "open-spending-50219f7e",
        		"description" => "In 2013 is de Open State Foundation gestart met het ontsluiten van financi\u00eble data van Amsterdam Stadsdeel Centrum in Openspending. Dit heeft eind 2015 geresulteerd in de duurzame ontsluiting van alle financi\u00eble data van Nederlandse regionale en lokale overheden als open data. De data vanaf 2010 is beschikbaar en nieuwe begrotingen en realisaties worden automatisch toegevoegd. Financi\u00eble transparantie is een belangrijke voorwaarde voor democratische controle en versterkt de informatiepositie van volksvertegenwoordigers, journalisten en inwoners. De data is beschikbaar als open data zodat iedereen zelf toepassingen en berekeningen met de data kan uitvoeren.\r\n\r\nOpen State heeft in 2014 alle gemeenten, provincies en waterschappen gevraagd om hun Iv3-gegevens (Informatie voor Derden) aan te leveren. Dit zijn financi\u00eble rapportages die elke lokale en regionale overheid periodiek naar het CBS stuurt. 203 overheden hebben daarop hun data aangeleverd, wat voor het CBS aanleiding was om als proef de financi\u00eble informatie van alle gemeenten van 2012 en 2013 te publiceren. Deze proef is succesvol verlopen en het CBS heeft nu de Iv3-gegevens van alle decentrale overheden als open data ontsloten.",
        		"image" => "http://www.openspending.nl/static/images/logo.svg",
        		"type" => "dataportaal",
        		"country" => "Nederland",
        		"organisation" => "Open State Foundation",
        		"website" => "http://www.openspending.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 24,
        		"group_id" => 5,
        		"name" => "Johan Groenen",
        		"slug" => "johan-groenen-50219f7e",
        		"description" => "Agile Coaching & Digital Services Strategie. Secretaris @CodeForNL: samenwerken aan de digitale overheid. Partner @TiltShift: Haal innovatie in huis! @APItecture\r\n\r\nAgile, HTML5, CSS, JavaScript, PHP, Linux, Apache, Open Data",
        		"image" => "https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAArrAAAAJDI3ZDk5NWNmLTk0OGUtNDQ2OS04YWU0LTVhYzRkNGMwYmJlYg.jpg",
        		"type" => "developer",
        		"country" => "Nederland",
        		"category" => "personen",
        		"organisation" => "TiltShift",
        		"website" => "http://www.jgroenen.nl",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 25,
        		"group_id" => 5,
        		"name" => "ICTU",
        		"slug" => "ictu-50219f7e",
        		"description" => "Samen met onze opdrachtgevers realiseren we kwalitatief hoogwaardige digitale dienstverlening. We verbinden kennis aan kunde, en oplossingen aan vraagstukken. Met oog voor de balans tussen techniek en gebruik, tussen innovatie en werkbare oplossingen. Zodat burgers en bedrijven zaken die ze doen met de overheid veilig en makkelijk digitaal kunnen afhandelen.\r\n\r\nAls onafhankelijke adviseur en uitvoerder binnen de overheid vinden we de juiste mix van expertise voor iedere opdracht. Zo profiteert de overheid \u00e9n de samenleving.",
        		"image" => "https://www.ictu.nl/themes/custom/ictu_theme/assets/images/logo.svg",
        		"type" => "stichting",
        		"country" => "Nederland",
        		"category" => "organisaties",
        		"organisation" => "ICTU",
        		"website" => "https://www.ictu.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 26,
        		"group_id" => 5,
        		"name" => "Transparent Water",
        		"slug" => "transparant-water-50219f7e",
        		"description" => "Kan ik uit de kraan drinken?\r\n\r\nVoer een adres in en ontdek welke waterkwaliteit je kunt verwachten. Voor alle stoffen en organismen die in het water voorkomen proberen wij aan te geven welk effect deze op jou hebben en of de gemeten waterkwaliteit goed of slecht voor je is.",
        		"image" => "http://media.istockphoto.com/photos/water-drop-picture-id530987380?k=6&m=530987380&s=612x612&w=0&h=qFv7VgyIkap9bJKEtX-UjsVs_fP5VYAD7i8FS237HI8=",
        		"type" => "community",
        		"country" => "Nederland",
        		"category" => "projecten",
        		"organisation" => "Code for NL",
        		"website" => "http://www.transparentwater.io/nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 27,
        		"group_id" => 5,
        		"name" => "Code for NL Slack",
        		"slug" => "code-for-nl-slack-50219f7e",
        		"description" => "Meepraten over Code for NL, meetups, technieken, projecten, etc.? Dat kan op Slack. Maak een account aan via <a href=\"http://praatmee.jgroenen.nl\">het aanmeld formulier</a>.",
        		"image" => "https://regmedia.co.uk/2016/01/12/slack.jpg?x=1200&y=794",
        		"type" => "platform",
        		"country" => "Nederland",
        		"category" => "tools",
        		"organisation" => "Code for NL",
        		"website" => "http://codefornl.slack.com",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 28,
        		"group_id" => 5,
        		"name" => "Waag Society",
        		"slug" => "waag-society-50219f7e",
        		"description" => "Waag Society \u2013 Institute for art, science and technology \u2013 is een pionier op het gebied van digitale media. In de afgelopen 22 jaar heeft de stichting zich ontwikkeld tot een instituut van internationale statuur, een platform voor artistiek onderzoek, een katalysator van experimenten en evenementen en een broedplaats voor culturele en sociale innovatie. ",
        		"image" => "http://content.stimuleringsfonds.nl/files/pro/i_1812/logo_waag.png",
        		"type" => "stichting",
        		"country" => "Nederland",
        		"category" => "organisaties",
        		"organisation" => "Waag Society",
        		"website" => "http://waag.org/nl",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 29,
        		"group_id" => 5,
        		"name" => "Discipl",
        		"slug" => "discipl-50219f7e",
        		"description" => "DIStributed Collaborative Information PLatform",
        		"image" => "https://discipl.org/wp-content/uploads/sites/17/2017/02/discipl-xl-300x300.png",
        		"type" => "platform",
        		"country" => "Nederland",
        		"category" => "projecten",
        		"organisation" => "ICTU",
        		"website" => "https://discipl.org/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 30,
        		"group_id" => 5,
        		"name" => "Amsterdam City Data",
        		"slug" => "amsterdam-city-data-50219f7e",
        		"description" => "Amsterdam City Data van Datapunt Amsterdam. Amsterdam beschikt over een schat aan gegevens over de stad. Via dit dataportaal stellen wij, in samenwerking met onze partners, deze gegevens beschikbaar. Samen met u willen wij werken aan vernieuwende datatoepassingen voor Amsterdam als leefbare stad.",
        		"image" => "https://zoek.officielebekendmakingen.nl/stcrt-2014-37951-1.png",
        		"type" => "dataportaal",
        		"country" => "Nederland",
        		"category" => "projecten",
        		"organisation" => "Gemeente Amsterdam",
        		"website" => "https://data.amsterdam.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 31,
        		"group_id" => 5,
        		"name" => "Code for NL",
        		"slug" => "code-for-nl-50219f7e",
        		"description" => "Stichting Code for NL is het Nederlandse netwerk van open source developers en designers die samenwerken aan de digitale overheid.\r\nOnze doelstelling is bijdragen aan de succesvolle digitale transformatie van gemeenten, andere overheden en de samenleving als geheel.",
        		"image" => "http://www.codefor.nl/img/larger_CfNL.png",
        		"type" => "stichting",
        		"country" => "Nederland",
        		"category" => "organisaties",
        		"organisation" => "Code for NL",
        		"website" => "http://www.codefor.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 32,
        		"group_id" => 5,
        		"name" => "Dataportaal van de Nederlandse overheid",
        		"slug" => "dataportaal-van-de-nederlandse-overheid-50219f7e",
        		"description" => "Dit dataportaal van de Rijksoverheid maakt datasets van alle Nederlandse overheden vindbaar. Dit doen we door te functioneren als register \u00e9n als centrale vindplaats van overheidsdata. We werken samen met ministeries, gemeenten, waterschappen en provincies aan het open stellen van data. Natuurlijk bieden we daarbij ook ondersteuning en leveren we informatie aan wie meer wil weten.",
        		"image" => "https://data.overheid.nl/sites/all/themes/koop2/images/logo.png",
        		"type" => "dataportaal",
        		"country" => "Nederland",
        		"category" => "tools",
        		"organisation" => "Ministerie van Binnenlandse Zaken en Koninkrijksrelaties",
        		"website" => "https://data.overheid.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 35,
        		"group_id" => 5,
        		"name" => "Datalab Amsterdam",
        		"slug" => "datalab-amsterdam-50219f7e",
        		"description" => "DataLab is een werkplaats, kenniscentrum en open podium. Voor data professionals en een in data ge\u00efnteresseerd publiek. Een plek voor slim, innovatief en zorgvuldig data gebruik.",
        		"image" => "http://community.knowledgemile.org/blobs/gebiedsplatform/78210/2016/8/datalab_amsterdam_logo.png",
        		"type" => "werkruimte",
        		"country" => "Nederland",
        		"category" => "projecten",
        		"organisation" => "Gemeente Amsterdam",
        		"website" => "datalabamsterdam.nl",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 36,
        		"group_id" => 5,
        		"name" => "Gebruiker Centraal",
        		"slug" => "gebruiker-centraal-50219f7e",
        		"description" => "De overheidsbrede kenniscommunity Gebruiker Centraal wil een gebruiksvriendelijke online overheid. Via evenementen en projecten leren we van elkaars ervaringen en doen we idee\u00ebn op. We leggen daarbij verbindingen naar aansluitende initiatieven en naar het bedrijfsleven. Online delen we methoden & technieken, cases en tips met elkaar. Lees verder over Gebruiker Centraal.",
        		"image" => "http://www.gebruikercentraal.nl/wp-content/uploads/2015/04/GebruikerCentraalLogoMetSlogan400px.png",
        		"type" => "programma",
        		"country" => "Nederland",
        		"category" => "organisatie",
        		"organisation" => "Gebruiker Centraal",
        		"website" => "http://www.gebruikercentraal.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 37,
        		"group_id" => 5,
        		"name" => "Digicommissaris",
        		"slug" => "digicommissaris-50219f7e",
        		"description" => "Op 1 augustus 2014 is Bas Eenhoorn gestart als Digicommissaris. Hij is door het kabinet tijdelijk (voor vier jaar) aangesteld om als overheidsbrede regisseur regie te voeren op de (door)ontwikkeling van de generieke digitale infrastructuur.",
        		"image" => "https://pbs.twimg.com/profile_images/686819484238266368/1HFeNJzY.jpg",
        		"type" => "digicommissaris",
        		"country" => "Nederland",
        		"category" => "personen",
        		"organisation" => "Digicommissaris",
        		"website" => "https://www.digicommissaris.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 38,
        		"group_id" => 5,
        		"name" => "Bureau Digicommissaris",
        		"slug" => "bureau-digicommissaris-50219f7e",
        		"description" => "Het Bureau van de Digicommissaris ondersteunt Bas Eenhoorn in zijn regievoerende werkzaamheden. Bureau Digicommissaris verbindt alle overheidslagen met \u00e9\u00e9n gemeenschappelijk doel: het realiseren van een veilige en betrouwbare digitale overheid.",
        		"image" => "https://www.digicommissaris.nl/image/2016/1/8/dc_bureau.jpg%28%29%28061B3F44AB7125E2496764BE6A5D5E74%29.jpg",
        		"type" => "overheid",
        		"country" => "Nederland",
        		"category" => "organisaties",
        		"organisation" => "Digicommissaris",
        		"website" => "https://www.digicommissaris.nl/bureau",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 39,
        		"group_id" => 5,
        		"name" => "Generieke Digitale Infrastructuur (GDI)",
        		"slug" => "generieke-digitale-infrastructuur-gdi-50219f7e",
        		"description" => "De Generieke Digitale Infrastructuur (GDI) legt de basis voor de digitale transformatie van de Nederlandse overheid. De GDI bestaat uit digitale basisvoorzieningen waarmee overheidsorganisaties hun primaire processen kunnen inrichten. Omdat de transformatie naar een digitale dienstverlening alle organisaties op verschillende manieren raakt, wordt de GDI als een serie losse componenten aangeboden.",
        		"image" => "http://www.digicommissaris.nl/image/2016/1/9/wereldbol-708289165.jpg%28%29%28crop-%2B1372%2B555%29%28mediaclass-facebook-og.75476a0dc140accd5c88a86489d839cda0813029%29%2829644CA2864A9DA1D4D7ADC33C675D09%29.jpg",
        		"type" => "infrastructuur",
        		"country" => "Nederland",
        		"category" => "projecten",
        		"organisation" => "Digicommissaris",
        		"website" => "https://www.digicommissaris.nl/over",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 40,
        		"group_id" => 23,
        		"name" => "RescaleEU",
        		"slug" => "rescaleeu-50219f7e",
        		"description" => "Herstel en behoud van locale ecosystemen. Natuurlijke, sociale en economische. Een grassroots beweging voor schaalverkleining.",
        		"type" => "merk",
        		"country" => "Nederland",
        		"category" => "organisatie",
        		"organisation" => "RescaleEU",
        		"website" => "http://www.rescale.eu/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 41,
        		"group_id" => 23,
        		"name" => "Herenboeren",
        		"slug" => "herenboeren-50219f7e",
        		"description" => "Herenboeren Nederland is een beweging van professionals die aantoont dat de productie van ons dagelijks voedsel anders, beter en bovenal duurzamer kan. We doen dat door het bieden van ondersteuning en het vergaren en ontsluiten van kennis voor de verdere ontwikkeling van Herenboerderijen in Nederland.\r\n\r\nWe zien grote kansen voor deze co\u00f6peratieve boerderijen die burgers gedeeld eigenaar maken van hun eigen boerderij; consumenten dus die samen vraaggestuurd produceren en consumeren. We helpen hen bij de ontwikkeling van deze kleinschalige gemengde bedrijven die duurzaam, gezond en bovenal smakelijk eten produceren.",
        		"image" => "http://www.herenboeren.nl/static/_assets/img/payoff.png",
        		"type" => "vereniging",
        		"country" => "Nederland",
        		"category" => "organisatie",
        		"organisation" => "Herenboeren",
        		"website" => "http://www.herenboeren.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 42,
        		"group_id" => 5,
        		"name" => "Vurb Foundation",
        		"slug" => "vurb-foundation-50219f7e",
        		"description" => "We propose, create and maintain code, design and policy. Our projects range from speculative to prototypes to mature and production grade.\r\n\r\nOur projects are open source, free to use and in the public interest.\r\n\r\nAll of our projects are available at GitHub.com/VurbFoundation.",
        		"type" => "stichting",
        		"country" => "Nederland",
        		"category" => "organisaties",
        		"organisation" => "Vurb Foundation",
        		"website" => "http://vurb.foundation",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ],[
            "id" => 43,
        		"group_id" => 5,
        		"name" => "Delta10",
        		"slug" => "delta10-50219f7e",
        		"description" => "Delta10 ontwikkelt software in samenwerking met overheden. Deze software is vrij beschikbaar voor iedereen en kan gemakkelijk worden hergebruikt door andere overheden. Ons doel is dat de overheid meer controle krijgt over haar ICT.",
        		"image" => "https://delta10.nl/static/img/logo.svg",
        		"type" => "bedrijf",
        		"country" => "Nederland",
        		"category" => "organisaties",
        		"organisation" => "Delta10",
        		"website" => "https://delta10.nl/",
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s')
          ]
        ];

        $table = $this->table('projects');
        $table->insert($data)->save();
    }
}
